version: '3.8'

services:
  bot-syscor:
    build: .
    image: bot-syscor-sharepoint:v1
    container_name: bot_syscor_sharepoint
    restart: unless-stopped
    # Define o fuso horário correto (BRT)
    environment:
      - TZ=America/Sao_Paulo
    # Volume opcional: se quiser persistir downloads (não essencial pois o script limpa)
    volumes:
      - syscor_downloads:/app/downloads

volumes:
  syscor_downloads:
